// Anime series and films; intentionally capped at64 independently of Anime Characters.
export const ANIME_TITLES = Object.freeze([
  "Death Note",
  "Naruto",
  "Naruto Shippuden",
  "One Piece",
  "Solo Leveling",
  "Vinland Saga",
  "Attack on Titan",
  "Blue Period",
  "Dr. Stone",
  "Haikyu!!",
  "Hunter x Hunter",
  "Kuroko's Basketball",
  "My Hero Academia",
  "One-Punch Man",
  "100 Meters",
  "A Silent Voice",
  "Erased",
  "The Promised Neverland",
  "Darwin's Game",
  "Jujutsu Kaisen",
  "Monster",
  "Spy x Family",
  "Sword Art Online",
  "Dragon Ball",
  "Dragon Ball Z",
  "Fullmetal Alchemist: Brotherhood",
  "Demon Slayer: Kimetsu no Yaiba",
  "Bleach",
  "Code Geass: Lelouch of the Rebellion",
  "Cowboy Bebop",
  "Steins;Gate",
  "Neon Genesis Evangelion",
  "Samurai Champloo",
  "Mob Psycho 100",
  "Chainsaw Man",
  "Frieren: Beyond Journey's End",
  "Delicious in Dungeon",
  "Blue Lock",
  "Slam Dunk",
  "Hajime no Ippo",
  "Ping Pong the Animation",
  "March Comes in Like a Lion",
  "Your Lie in April",
  "Violet Evergarden",
  "Clannad",
  "Fruits Basket (2019)",
  "Toradora!",
  "Kaguya-sama: Love Is War",
  "Bocchi the Rock!",
  "Made in Abyss",
  "Mushishi",
  "Natsume's Book of Friends",
  "Durarara!!",
  "Baccano!",
  "Gurren Lagann",
  "Trigun (1998)",
  "Hellsing Ultimate",
  "Psycho-Pass",
  "Fate/Zero",
  "Princess Mononoke",
  "Spirited Away",
  "Your Name",
  "Weathering with You",
  "Akira"
]);

