import { ADDITIONAL_CATEGORIES } from './additional-categories.mjs?v=1';

// Both modes share these pools. User lists may exceed 100; Movies awaits user input.
export const CATEGORIES = [
  { id: 'nba', name: 'NBA Players', items: [
    'LeBron James', 'Stephen Curry', 'Shai Gilgeous-Alexander', 'Nikola Jokić', 'Giannis Antetokounmpo',
    'Kevin Durant', 'Luka Dončić', 'Anthony Edwards', 'Cade Cunningham', 'Jalen Brunson',
    'Joel Embiid', 'James Harden', 'Jimmy Butler', 'Kawhi Leonard', 'Scottie Barnes',
    'Victor Wembanyama', 'Donovan Mitchell', 'Jayson Tatum', 'Devin Booker', 'Cooper Flagg',
    'Tyrese Maxey', 'Jaylen Brown', 'Jalen Johnson', 'Karl-Anthony Towns', 'Tyrese Haliburton',
    'Jalen Williams', 'Alperen Şengün', 'Chet Holmgren', 'Jamal Murray', 'Amen Thompson',
    'Ausar Thompson', 'Evan Mobley', 'Paolo Banchero', 'Austin Reaves', 'Stephon Castle',
    'Zion Williamson', 'LaMelo Ball', 'Bam Adebayo', 'Pascal Siakam', 'Trae Young',
    'Kon Knueppel', 'Deni Avdija', 'Anthony Davis', 'Lauri Markkanen', 'Domantas Sabonis',
    'Jalen Duren', 'Dylan Harper', 'VJ Edgecombe', 'Franz Wagner', 'Julius Randle',
    'De’Aaron Fox', 'Rudy Gobert', 'Derrick White', 'Payton Pritchard', 'Brandon Ingram',
    'Kyrie Irving', 'Damian Lillard', 'OG Anunoby', 'Darius Garland', 'Jarrett Allen',
    'AJ Dybantsa', 'Jaren Jackson Jr.', 'Josh Giddey', 'Tyler Herro', 'Desmond Bane',
    'Klay Thompson', 'Draymond Green', 'Ja Morant', 'Norman Powell', 'Ivica Zubac',
    'Mikal Bridges', 'Cameron Johnson', 'Kristaps Porziņģis', 'Keyonte George', 'Myles Turner',
    'Cason Wallace', 'Aaron Gordon', 'Michael Porter Jr.', 'Naz Reid', 'Devin Vassell',
    'Jaden McDaniels', 'Jabari Smith Jr.', 'Zach LaVine', 'DeMar DeRozan', 'Nickeil Alexander-Walker',
    'Jalen Green', 'Dillon Brooks', 'RJ Barrett', 'Cameron Boozer', 'Darryn Peterson',
    'Darius Acuff Jr.', 'Caleb Wilson', 'Alex Sarr', 'Will Riley',
    'Russell Westbrook', 'Dejounte Murray', 'CJ McCollum', 'Tobias Harris', 'Brook Lopez', 'Bobby Portis',
  ] },
  { id: 'anime', name: 'Anime Characters', items: [
    // Naruto
    'Minato Namikaze', 'Itachi Uchiha', 'Sakura Haruno',
    'Shisui Uchiha', 'Kakashi Hatake', 'Naruto Uzumaki',
    'Sakumo Hatake', 'Sasuke Uchiha', 'Madara Uchiha',
    'Hinata Hyuga', 'Obito Uchiha (Tobi)', 'Jiraiya',
    'Shikamaru Nara', 'Tobirama Senju', 'Gaara',
    'Hashirama Senju', 'Deidara', 'Neji Hyuga',
    'Sasori', 'Rock Lee', 'Might Guy',
    'Kurama', 'Orochimaru', 'Hidan',
    'Kushina Uzumaki', 'Iruka Umino', 'Fugaku Uchiha',
    'Tsunade',
    // One Piece
    'Monkey D. Luffy', 'Roronoa Zoro', 'Sanji',
    'Brook', 'Nico Robin', 'Jinbe',
    'Donquixote Doflamingo', 'Dracule Mihawk', 'Boa Hancock',
    'Crocodile', 'Gecko Moria', 'Trafalgar Law',
    'Eustass Kid', 'Monkey D. Garp', 'Smoker',
    'Marshall D. Teach (Blackbeard)', 'Shanks', 'Edward Newgate (Whitebeard)',
    'Kaido', 'Charlotte Linlin (Big Mom)', 'Gol D. Roger',
    'Sengoku', 'Kuzan (Aokiji)', 'Sakazuki (Akainu)',
    'Issho (Fujitora)', 'Borsalino (Kizaru)', 'Aramaki (Ryokugyu)',
    'Usopp',
    // Hunter × Hunter
    'Meruem', 'Gon Freecss', 'Isaac Netero',
    'Neferpitou', 'Menthuthuyoupi (Youpi)', 'Shaiapouf',
    'Chrollo Lucilfer', 'Silva Zoldyck', 'Zeno Zoldyck',
    'Hisoka Morow', 'Illumi Zoldyck', 'Kurapika',
    'Biscuit Krueger', 'Kite', 'Feitan',
    'Morel', 'Uvogin', 'Phinks',
    // Solo Leveling
    'Sung Jinwoo',
    // One-Punch Man
    'Saitama', 'Garou', 'Blast',
    'Boros', 'Tatsumaki', 'Sage Centipede',
    'Flashy Flash', 'Metal Knight', 'Silver Fang (Bang)',
    'Atomic Samurai', 'Genos', 'Superalloy Darkshine',
    'Metal Bat', 'Drive Knight', 'Watchdog Man',
    'Child Emperor', 'Pig God', 'Zombieman',
    // The Seven Deadly Sins
    'Meliodas', 'Escanor', 'Ban',
    // Jujutsu Kaisen
    'Ryomen Sukuna', 'Satoru Gojo', 'Yuta Okkotsu',
    'Yuji Itadori', 'Toji Fushiguro', 'Jogo',
    'Mahito', 'Hiromi Higuruma', 'Ryu Ishigori',
    'Takako Uro', 'Megumi Fushiguro',
    // My Hero Academia
    'Izuku Midoriya (Deku)', 'Tomura Shigaraki', 'All Might',
    'All For One', 'Star and Stripe', 'Katsuki Bakugo',
    'Endeavor', 'Shoto Todoroki', 'Dabi',
    'Best Jeanist', 'Mirio Togata', 'Stain',
    // Additional named Akatsuki members
    'Nagato (Pain)', 'Konan', 'Kisame Hoshigaki',
    'Kakuzu', 'Black Zetsu', 'White Zetsu',
    'Yahiko', 'Juzo Biwa', 'Kyusuke',
    'Daibutsu', 'Kie',
    // Additional on-screen Kage
    'Hiruzen Sarutobi', 'Danzo Shimura', 'Reto',
    'Shamon', 'Third Kazekage', 'Rasa',
    'Byakuren', 'Gengetsu Hozuki', 'Third Mizukage',
    'Yagura Karatachi', 'Mei Terumi', 'Chojuro',
    'Ishikawa', 'Mu', 'Onoki',
    'Kurotsuchi', 'First Raikage', 'Second Raikage',
    'Third Raikage', 'Ay (Fourth Raikage)', 'Darui',
  ] },
  { id: 'movies', name: 'Movies', pending: true, items: [] },
  ...ADDITIONAL_CATEGORIES,
];
