// Literal, family-friendly prompts. Keep every category and item list immutable.
export const PROMPT_CATEGORIES = Object.freeze([
  Object.freeze({
    id: 'animals',
    name: 'Animals',
    items: Object.freeze([
      'Elephant',
      'Giraffe',
      'Penguin',
      'Kangaroo',
      'Monkey',
      'Gorilla',
      'Sloth',
      'Flamingo',
      'Peacock',
      'Ostrich',
      'Owl',
      'Eagle',
      'Duck',
      'Rooster',
      'Parrot',
      'Dolphin',
      'Shark',
      'Octopus',
      'Crab',
      'Seal',
      'Walrus',
      'Turtle',
      'Crocodile',
      'Snake',
      'Frog',
      'Chameleon',
      'Butterfly',
      'Bee',
      'Spider',
      'Ant',
      'Rabbit',
      'Horse',
      'Cow',
      'Pig',
      'Goat',
      'Cat',
      'Dog',
      'Mouse',
      'Hedgehog',
      'Raccoon',
    ]),
  }),
  Object.freeze({
    id: 'actions',
    name: 'Everyday actions',
    items: Object.freeze([
      'Brushing your teeth',
      'Washing your hair',
      'Tying your shoes',
      'Getting dressed',
      'Ironing a shirt',
      'Folding laundry',
      'Making the bed',
      'Vacuuming the floor',
      'Washing dishes',
      'Taking out the trash',
      'Watering plants',
      'Walking the dog',
      'Feeding a baby',
      'Changing a diaper',
      'Cooking noodles',
      'Chopping vegetables',
      'Rolling dough',
      'Flipping a pancake',
      'Peeling a banana',
      'Eating with chopsticks',
      'Blowing out birthday candles',
      'Wrapping a gift',
      'Reading a book',
      'Writing a letter',
      'Typing on a keyboard',
      'Taking a selfie',
      'Making a phone call',
      'Listening to music',
      'Hailing a taxi',
      'Driving a car',
      'Riding an escalator',
      'Buying groceries',
      'Unlocking a door',
      'Opening a stubborn jar',
      'Packing a suitcase',
      'Putting up a tent',
      'Hanging a picture',
      'Sewing on a button',
      'Blowing your nose',
      'Yawning and stretching',
    ]),
  }),
  Object.freeze({
    id: 'objects',
    name: 'Objects',
    items: Object.freeze([
      'Umbrella',
      'Binoculars',
      'Telescope',
      'Magnifying glass',
      'Flashlight',
      'Candle',
      'Alarm clock',
      'Hourglass',
      'Compass',
      'Globe',
      'Backpack',
      'Wallet',
      'Sunglasses',
      'Necktie',
      'Rain boots',
      'Mittens',
      'Crown',
      'Mask',
      'Hair dryer',
      'Electric fan',
      'Remote control',
      'Camera',
      'Calculator',
      'Printer',
      'Toaster',
      'Blender',
      'Rolling pin',
      'Corkscrew',
      'Scissors',
      'Stapler',
      'Hammer',
      'Ladder',
      'Wheelbarrow',
      'Shopping cart',
      'Rocking chair',
      'Hammock',
      'Kite',
      'Yo-yo',
      'Accordion',
      'Violin',
    ]),
  }),
  Object.freeze({
    id: 'jobs',
    name: 'Jobs',
    items: Object.freeze([
      'Firefighter',
      'Paramedic',
      'Doctor',
      'Dentist',
      'Veterinarian',
      'Pharmacist',
      'Teacher',
      'Librarian',
      'Scientist',
      'Astronaut',
      'Pilot',
      'Flight attendant',
      'Bus driver',
      'Train conductor',
      'Mail carrier',
      'Delivery courier',
      'Chef',
      'Baker',
      'Server',
      'Barista',
      'Cashier',
      'Farmer',
      'Beekeeper',
      'Gardener',
      'Fisher',
      'Carpenter',
      'Plumber',
      'Electrician',
      'Mechanic',
      'Construction worker',
      'Window cleaner',
      'Hairdresser',
      'Tailor',
      'Photographer',
      'Painter',
      'Sculptor',
      'Orchestra conductor',
      'Magician',
      'News reporter',
      'Lifeguard',
    ]),
  }),
  Object.freeze({
    id: 'sports',
    name: 'Sports',
    items: Object.freeze([
      'Basketball',
      'Soccer',
      'American football',
      'Baseball',
      'Cricket',
      'Rugby',
      'Volleyball',
      'Tennis',
      'Badminton',
      'Table tennis',
      'Golf',
      'Ice hockey',
      'Field hockey',
      'Lacrosse',
      'Bowling',
      'Curling',
      'Archery',
      'Fencing',
      'Boxing',
      'Sumo wrestling',
      'Karate',
      'Gymnastics',
      'Weightlifting',
      'High jump',
      'Pole vault',
      'Javelin throw',
      'Swimming',
      'Diving',
      'Rowing',
      'Surfing',
      'Skiing',
      'Snowboarding',
      'Figure skating',
      'Skateboarding',
      'Rock climbing',
    ]),
  }),
  Object.freeze({
    id: 'movies-tv',
    name: 'Movies & TV',
    items: Object.freeze([
      'Jurassic Park',
      'Titanic',
      'Star Wars',
      'The Lord of the Rings',
      'Back to the Future',
      'Ghostbusters',
      'Home Alone',
      'The Karate Kid',
      'The Wizard of Oz',
      'Charlie and the Chocolate Factory',
      'Mary Poppins',
      'The Sound of Music',
      'Singin\' in the Rain',
      'The Greatest Showman',
      'High School Musical',
      'Frozen',
      'Moana',
      'Encanto',
      'Coco',
      'Inside Out',
      'Toy Story',
      'Finding Nemo',
      'WALL-E',
      'How to Train Your Dragon',
      'Kung Fu Panda',
      'Ratatouille',
      'Spirited Away',
      'My Neighbor Totoro',
      'The Jungle Book',
      'Pirates of the Caribbean',
      'The Great British Bake Off',
      'Sesame Street',
      'Bluey',
      'SpongeBob SquarePants',
      'Avatar: The Last Airbender',
    ]),
  }),
  Object.freeze({
    id: 'characters',
    name: 'Characters',
    items: Object.freeze([
      'Superman',
      'Batman',
      'Wonder Woman',
      'Spider-Man',
      'The Hulk',
      'Iron Man',
      'Captain America',
      'Black Panther',
      'Thor',
      'The Flash',
      'Wolverine',
      'Harry Potter',
      'Hermione Granger',
      'Sherlock Holmes',
      'Robin Hood',
      'Peter Pan',
      'Tinker Bell',
      'Cinderella',
      'Snow White',
      'Rapunzel',
      'Pinocchio',
      'Little Red Riding Hood',
      'The Cat in the Hat',
      'Winnie the Pooh',
      'Mickey Mouse',
      'Bugs Bunny',
      'Scooby-Doo',
      'Shrek',
      'Super Mario',
      'Paddington Bear',
      'Sonic the Hedgehog',
      'Pikachu',
      'Naruto Uzumaki',
      'Monkey D. Luffy',
      'Santa Claus',
    ]),
  }),
  Object.freeze({
    id: 'tricky',
    name: 'Tricky scenarios',
    items: Object.freeze([
      'Walking against a strong wind',
      'Slipping on a banana peel',
      'Stepping on a squeaky toy',
      'Trying to stay awake in class',
      'Sneaking past a sleeping dragon',
      'Being chased by a swarm of bees',
      'Finding a spider in your shoe',
      'Getting caught in a revolving door',
      'Trying to catch a runaway balloon',
      'Getting stuck in quicksand',
      'Walking on the moon',
      'Riding a roller coaster',
      'Trying to walk in oversized shoes',
      'Balancing too many plates',
      'Carrying a very heavy invisible box',
      'Eating something extremely sour',
      'Burning your tongue on hot soup',
      'Brain freeze from ice cream',
      'Having the hiccups during a speech',
      'Sneezing while holding a full cup',
      'Trying to swat a buzzing mosquito',
      'Looking for lost glasses on your head',
      'Untangling a giant knot',
      'Trying to put toothpaste back in the tube',
      'Building furniture with confusing instructions',
      'A robot running out of batteries',
      'A snowman melting in the sun',
      'A statue coming to life',
      'A mime trapped in an invisible box',
      'A pirate discovering buried treasure',
      'A detective following mysterious footprints',
      'A superhero learning to fly',
      'A wizard casting a spell that goes wrong',
      'A baby taking its first steps',
      'A penguin trying to dance ballet',
    ]),
  }),
]);
